### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by vaydingul** [JialeTao/MRFA#1]
Hey Jiale, thank you for the great work!
When do you plan to release the code?

Thx!

**Comment by JialeTao** [comment]
> Hey Jiale, thank you for the great work! When do you plan to release the code?
> 
> Thx!

Hi, thanks for your attention to our work. Currently I'm in a rush for the cvpr deadline. We will release the code as soon as the ddl is ended.

**Comment by vaydingul** [comment]
Ah, get it. Thank you for the quick response.

good luck!

**Comment by vaydingul** [comment]
Any expected update soon?

**Comment by JialeTao** [comment]
Hi @vaydingul, I'm trying to release the codes by this weekend.

**Comment by JialeTao** [comment]
> Any expected update soon?

Hi @vaydingul, thank you for your continual attention. We have now released the codes. The pretrained checkpoints will be available soon.

**Comment by vaydingul** [comment]
Oh, that's perfect. Thank you for your effort ❤️
