### ISSUE TITLE
Possibility of animating the face of a full body picture?

### ISSUE THREAD

**Issue by Valentino-L** [JialeTao/MRFA#2]
Hi! Many thanks for your work! I'm very interested to apply your work to full-body images, would it still produce good results or would the full-body image need to be cropped around the head first? Also, is it possible to animate the face of a video (a sequence of frames), assuming we only use one reference face image plus a full-body video of this person moving and talking? Thanks a lot!

**Comment by JialeTao** [comment]
Hi @Valentino-L, thanks for your attention to our work.

Firstly, the full-body image did need to be cropped around the head first, then the animated head could be pasted to the original image. We have tried this operation and produced e-commerce demos in a previous project [DAM](https://github.com/JialeTao/DAM). Secondly, it is possible to do this, but you may need to crop the face first.

**Comment by Valentino-L** [comment]
Thank you very much for your response. Now I'm trying to run your demo but it seems the command goes into an infinite loop and it does not stop nor produce any results. I'm in a conda environment with python 3.8 using H100 and I have installed all your dependency versions except for timm==0.9.16 and opencv-python=4.8.0.76 because it seems their older versions have been deprecated. Do you have any idea what cause this? Many thanks!

<img width="1203" alt="Screenshot 2024-02-24 at 12 22 28" src="https://github.com/JialeTao/MRFA/assets/67510831/fc67252d-c249-4af2-b295-25dec47368d0">

**Comment by JialeTao** [comment]
Hi @Valentino-L, maybe you could ctrl-c the command to see where the process goes. I didn't have this problem before.

**Comment by Valentino-L** [comment]
<img width="1023" alt="Screenshot 2024-02-25 at 20 52 46" src="https://github.com/JialeTao/MRFA/assets/67510831/0bd43633-3c5e-482e-a304-5a7e9f147f5d">

It seems there is a problem with importing dependencies... Do you have any idea how I could fix it? I think this error happened when I try to force install cuda 11.8. 

To install torch 1.10.1 according to official pytorch website, below is the command:

conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge

but it only supports up to cuda 11.3 however H100 requires minimal 11.8 to run so I just manually changed 11.3 to 11.8. Not sure if it's a good move

**Comment by Valentino-L** [comment]
Hi! I have solved that problem by installing cuda 12.1. Now everything works. Thanks a lot!
