### ISSUE TITLE
absolute keypoint coordinates

### ISSUE THREAD

**Issue by Mayy1994** [JialeTao/MRFA#5]
Hi, I have tried using absolute keypoint coordinates by disabling the "--relative" option, but the output appears to be very blurry. 
Could you please explain the reason behind this? Are there any specific areas in the code that require modification to address this issue? Thank you.

**Comment by JialeTao** [comment]
Hi @Mayy1994, could you show the source image, the driving video, and the generated results of absolute and relative animation?

**Comment by Mayy1994** [comment]
Thank you for your response. 

Below are the source image, driving video,result using "--relative --adapt_scale", and result disabling them. Please take a look, many thanks!

![aligned_src](https://github.com/JialeTao/MRFA/assets/40232175/c2179dbf-00c6-4982-8ce5-bc3c06f46fac)

https://github.com/JialeTao/MRFA/assets/40232175/aba5faf2-11d3-43a1-926b-503d8c1c5a99

https://github.com/JialeTao/MRFA/assets/40232175/8a27f048-e9ed-42fe-a541-62e178ccb8ef

https://github.com/JialeTao/MRFA/assets/40232175/fc6163bd-1e2b-4bf7-85de-65975fbc2c7c

**Comment by JialeTao** [comment]
Hi @Mayy1994, I have tested this image-video pair using the Voxceleb1 checkpoint with absolute animation, and I got the normal result, as in the following:


https://github.com/JialeTao/MRFA/assets/38600167/414c1ac8-aa78-4675-ab42-d48121c14671


BTW, what's the checkpoint you used for animation?

**Comment by Mayy1994** [comment]
Haha, thank you! It turns out that I used the wrong checkpoint (celebvhq.pth) for this test video. With vox.pth, the result is normal. 

Both the Voxceleb1 and CelebV-HQ datasets are talking head datasets, and CelebVHQ contains more data for training. Why are the results so different with the absolute coordinates? Could it be because the quality of my test video is closer to the Vox dataset?

**Comment by JialeTao** [comment]
I think the voxceleb1 dataset has a more diverse motion distribution than that of cvhq dataset, leading to a more robust motion transfer model.

**Comment by Mayy1994** [comment]
Thanks a lot for all your help!
